### ISSUE TITLE
securing gcs static website - routing rule not working as expected

### ISSUE THREAD

**Issue by irosgrim** [xiangshen-dk/securing-gcs-static-assets-iap#3]
I'm trying to follow https://cloud.google.com/community/tutorials/securing-gcs-static-website

( https://github.com/xiangshen-dk/securing-gcs-static-assets-iap )

The load balancer routing rule works only as long as i have the Cloud-CDN-Cookie or if Cloud-CDN-Cookie is the first cookie that is set but if i have more than one cookie and Cloud-CDN-Cookie is not the first cookie, the routing to the bucket is never done.

Any tips on how can i solve this?
Thank you.

**Comment by xiangshen-dk** [comment]
There is a feature request open for a regex rule match: https://issuetracker.google.com/issues/177618240, which can be a fix for the issue.

Also, as a workaround, we can use a longer path for the cookie order.  

Search the following text in README for the example:
```
Important: The path is needed here to make sure the CDN signed cookie will be the first in the cookie header string. It takes advantage of the fact that most browsers will sort the cookies from the longest path to the shortest path.
```

**Comment by irosgrim** [comment]
Oh, that last part I didn't see it in the original article.
Does it matter what i put in the path?

**Comment by xiangshen-dk** [comment]
No, it doesn't matter what's in the path. Only the path length matters.

**Comment by irosgrim** [comment]
thank you for your help!
