### ISSUE TITLE
Docker build error: grpcio

### ISSUE THREAD

**Issue by ignatiusm** [xiangshen-dk/securing-gcs-static-assets-iap#4]
Thank you for this repository - It is very helpful!

I was having an issue building the docker image. During the `grpcio` build step, I kept getting `FileNotFoundError: [Errno 2] No such file or directory: 'c++'` .

I tried a couple of fixes, but the one that ultimate worked came from [an issue in the grpcio repo](https://github.com/grpc/grpc/issues/28166).

I'll submit a PR with the suggested fix.

**Comment by ignatiusm** [comment]
PR is [here](https://github.com/xiangshen-dk/securing-gcs-static-assets-iap/pull/5/files)

**Comment by xiangshen-dk** [comment]
Appreciate your contribution!
